### ISSUE TITLE
This was a nice repo!

### ISSUE THREAD

**Issue by loneicewolf** [Sargastico/HookPatchStuff#1]
Thanks for making this repo, I found it interesting :)
This issue isn't a issue/or problem, it's just to tell you the repo is useful `:)` I will be watching it, I am a bit surprised that it's not watched so much by others.

Anyway! 

Wishes from Sweden!

<sub>
This repo can be closed, if needed 👍🏼

**Comment by Sargastico** [comment]
u are welcome! thank you for the feedback :)

It's always good to know that a repo helped someone

Wishes from Brazil!
